name: Docker image buildx and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: littledouzi/worker:latest
  deploy:
    runs-on: ubuntu-latest
    needs: Docker-Build-Push
    steps:
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: 80.251.212.50
          port: 29883
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
            curl -fsSL get.docker.com -o get-docker.sh
            chmod +x get-docker.sh
            ./get-docker.sh
            systemctl start docker
            docker version 
            docker container stop worker || true
            docker image pull littledouzi/worker:latest
            docker container run -d -p 51000-51299:51000-51299/tcp  --name worker littledouzi/worker:latest python server.py
